docs: add a contrition guide for `scripts/pr.sh`
rooch-network/rooch pull request #1073
Opened 2023-10-30 03:01 UTC by geometryolife

2023-10-30 03:04 UTC, geometryolife commented
#952

2023-11-02 15:05 UTC, jolestar requested changes

2023-11-02 15:05 UTC, jolestar commented on docs/website/pages/docs/contribution-guides/script-pr.zh-CN.mdx
> +```
这部分内容应该在 example guide 里。pr.sh 这个只介绍 pr.sh 的作用以及它的几个参数。

2023-11-04 01:54 UTC, jolestar approved these changes

2023-11-04 01:55 UTC, jolestar approved these changes

2023-11-04 01:55 UTC, jolestar commented on docs/website/pages/docs/contribution-guides/script-pr.zh-CN.mdx
> +./scripts/pr.sh -e
可以把 pr.sh 更多的检查功能都列举一下

2023-11-04 01:56 UTC, merged