init object counter
rooch-network/rooch pull request #1189
Opened 2023-11-29 17:47 UTC by geometryolife

2023-12-05 00:06 UTC, jolestar requested changes

2023-12-05 00:06 UTC, jolestar commented on docs/website/pages/docs/developer-guides/quick-start.zh-CN.mdx
> +        context::move_resource_to(ctx, owner, counter);
这个 Counter 需要是 Object<Counter>, 而不是把名字改成 ObjectCounter

2023-12-06 01:59 UTC, jolestar commented on docs/website/pages/docs/developer-guides/quick-start.zh-CN.mdx
> +    }
这里，如果全局只有一个 Object，可以用 `context::new_named_object` 来创建。这样传递参数的时候可以直接通过类型来传递。

可以同时提供两个：

1. 默认创建一个 named object,作为全局 object，这个 object 是 shared object，任何人都能修改。
2. 用户可以创建一个新的 Object，这个只能创建者修改。

2023-12-06 01:59 UTC, jolestar commented on docs/website/pages/docs/developer-guides/quick-start.zh-CN.mdx
> +    }
另外 Object id 可以通过 Event 发送出来。debug print 方式只能在本地开发使用。

2023-12-06 01:59 UTC, jolestar commented on docs/website/pages/docs/developer-guides/quick-start.zh-CN.mdx
> +rooch move run --function default::quick_start_object_counter::increase --args object_id:0xf049ae1d92f970ff1b9c397a49bb5f7c7668bfd5cf5b73035c183b574a7daabb
参数是 Object，所以可以用 `object:: 0xf049ae1d92f970ff1b9c397a49bb5f7c7668bfd5cf5b73035c183b574a7daabb` 传递参数

2023-12-06 01:59 UTC, jolestar commented on docs/website/pages/docs/developer-guides/quick-start.zh-CN.mdx
> +    struct ObjectCounter has key, store {
struct 的名字建议还是用 `Counter`

2023-12-06 03:27 UTC, geometryolife commented on docs/website/pages/docs/developer-guides/quick-start.zh-CN.mdx
> +    struct ObjectCounter has key, store {
好的

2023-12-09 23:42 UTC, geometryolife commented
@jolestar 看一下中文和例子合适了吗？

2023-12-10 05:52 UTC, jolestar commented
> @jolestar 看一下中文和例子合适了吗？

可以了

2023-12-12 02:10 UTC, jolestar approved these changes

2023-12-12 02:10 UTC, merged