feat: support list fields for object.move
rooch-network/rooch pull request #3142
Opened 2024-12-31 11:54 UTC by lispking

2025-01-02 08:40 UTC, jolestar commented on frameworks/moveos-stdlib/src/natives/moveos_stdlib/object/object_field_fn.rs
> +                smallvec![Value::vector_for_testing_only(value)],
The return types cause the UNKNOWN_INVARIANT_VIOLATION_ERROR.

2025-01-02 08:40 UTC, jolestar commented on moveos/moveos-object-runtime/src/runtime_object.rs
> +            self.list_field_objects_from_db(layout_loader, resolver, cursor, limit)?;
The result is empty, because the current transaction data do not write to db yet, so we need to scan the RuntimeObject fields first.

But the RuntimeObject fields may be part of fields from db, how to handle the cursor is a problem.

2025-01-02 08:40 UTC, jolestar commented on moveos/moveos-object-runtime/src/runtime_object.rs
> +                    cached_field.borrow_value(Some(&expect_value_type))?,
We use borrow there, the return value should be `&V`? But Move does not support `vector<&V>` yet. Maybe we should support `list_field_names` in Move, and the Move code to `borrow_field` via the name.

2025-01-03 03:28 UTC, jolestar commented on frameworks/moveos-stdlib/sources/object.move
> +    fun list_field_keys<T: key>(obj: &Object<T>): vector<address> {
Should we support pagination? if the object has too many fields, this call will out_of_gas

2025-01-03 03:28 UTC, jolestar commented on frameworks/moveos-stdlib/sources/object.move
> +    native fun native_list_field_keys<V>(obj_id: ObjectID): vector<V>;
remove the type_param `V` we can directly return `vector<address>`

2025-01-03 05:40 UTC, steelgeek091 commented on frameworks/moveos-stdlib/src/natives/moveos_stdlib/object/object_field_fn.rs
> +    pub base: InternalGas,
关于 gas 设置有以下节点要修改：

1. native 函数的 Gas 参数的类型需要 `Option` 类型，每个参数初始化需要用 `Some(0.into)`，参考文件 `frameworks/moveos-stdlib/src/natives/moveos_stdlib/base64.rs` ；
2. 需要为每个 Gas 参数指定一个 `0` 初始值，参考文件 `frameworks/rooch-framework/src/natives/gas_parameter/base64.rs` ；
3. 在 `crates/rooch-genesis/src/lib.rs` 文件中增加 `FrameworksGasParameters::v3()`，在这个函数中，将 `FrameworksGasParameters::v2()` 的值进一步修改，设置上面增加的 Gas 参数的真正的 gas 计费值，可以参考 `FrameworksGasParameters::v1()` 中的写法。最后将 `FrameworksGasParameters::latest()` 指向 `FrameworksGasParameters::v3()`。

建议设置 `base` 值为 1000，`per_byte_serialized` 设置为 150。

2025-01-03 05:44 UTC, steelgeek091 requested changes

2025-01-03 05:44 UTC, steelgeek091 commented on frameworks/moveos-stdlib/src/natives/moveos_stdlib/object/object_field_fn.rs
> +    pub per_byte_serialized: InternalGasPerByte,
关于 gas 设置有以下节点要修改：

1. native 函数的 Gas 参数的类型需要 `Option` 类型，每个参数初始化需要用 `Some(0.into)`，参考文件 `frameworks/moveos-stdlib/src/natives/moveos_stdlib/base64.rs` ；
2. 需要为每个 Gas 参数指定一个 `0` 初始值，参考文件 `frameworks/rooch-framework/src/natives/gas_parameter/base64.rs` ；
3. 在 `crates/rooch-genesis/src/lib.rs` 文件中增加 `FrameworksGasParameters::v3()`，在这个函数中，将 `FrameworksGasParameters::v2()` 的值进一步修改，设置上面增加的 Gas 参数的真正的 gas 计费值，可以参考 `FrameworksGasParameters::v1()` 中的写法。最后将 `FrameworksGasParameters::latest()` 指向 `FrameworksGasParameters::v3()`。

建议设置 `base` 值为 1000，`per_byte_serialized` 设置为 150。

2025-01-03 07:24 UTC, jolestar commented on moveos/moveos-object-runtime/src/runtime_object.rs
> +            .take(limit)
这样做无法保证 list_field_keys 结果的稳定性。应该这样实现：

1. 先从 db 加载数据。
2. 如果 db 中的数据不够 limit，则遍历 fields，找出其中 Fresh 的 field，补充在最后面。

2025-01-03 09:18 UTC, steelgeek091 commented on frameworks/rooch-framework/src/natives/gas_parameter/object_list_field_keys.rs
> +    [.list_field_keys.per_byte, optional "list_field_keys.per_byte", 150 * MUL],
we should set these two value to 0.

2025-01-03 12:18 UTC, steelgeek091 approved these changes

2025-01-04 03:13 UTC, jolestar reviewed
需要构造一个测试用例：

第一个交易写 fields，第二个交易写并且读 fields。

测试目标：

1. 测试从 db 中加载的场景。
2. 测试如果 RuntimeObject 的 fields 中混合了 fresh 和 cached fields 后的翻页。
3. 同一个交易中，数据有变化的情况下，多次遍历的结果是否一致。

这种测试需要通过集成测试来实现，参看 https://github.com/rooch-network/rooch/blob/be131eef2bb313c19d45c84ac5832ba96fbdbb69/crates/rooch-framework-tests/tests/cases

2025-01-04 03:13 UTC, jolestar commented on frameworks/moveos-stdlib/sources/object.move
> +    fun list_field_keys<T: key>(obj: &Object<T>, cursor: Option<address>, limit: u64): vector<address> {
这个 fun 暂时不 public，不过可以先 `public(friend)` 让 `table` 模块用这个 fun 来尝试提供遍历方法。

2025-01-04 10:03 UTC, jolestar commented on frameworks/moveos-stdlib/sources/table.move
> +    }
但 table 并不能通过 FieldKey 来 borrow, 这里 list 出来后没有办法使用，这个还不太好设计。如果增加 borrow_by_key 的方法，就有点冗余了。

感觉可以提供一个 Iterator struct，list 返回 Iterator?

```
struct Iterator<K,V>{
  handle: ObjectID,
  cursor: Option<address>,
  limit: u64,
  keys: vector<address>,
}
``` 

```
public fun next(&mut Iterator<K,V>): &V;
public fun next_mut(&mut Iterator<K,V>): &mut V;
```

这样把 cursor 的逻辑也封装进去了。不过可行性估计要代码验证一下。

2025-01-04 15:22 UTC, jolestar commented on frameworks/moveos-stdlib/sources/table.move
> +    public fun drop_iterator<K: copy + drop + store, V:store>(iterator: Iterator<K, V>) {
给 Iterator 加上 `drop`? 这样就不需要这个方法了。

2025-01-04 15:22 UTC, jolestar commented on frameworks/moveos-stdlib/sources/object.move
> +    public(friend) fun borrow_field_key_internal<Name: copy + drop + store, Value>(obj_id: ObjectID, field_key: address): &Value {
这里是不是返回 `DynamicField` 比较合适。这样调用方也能拿到 Name，不然不知道 field_key 对应点 name 是什么。另外名字叫做 `borrow_field_with_key_internal` 是不是更合适一些。

2025-01-04 15:22 UTC, jolestar commented on frameworks/moveos-stdlib/sources/object.move
> +    public(friend) fun borrow_mut_field_key_internal<Name: copy + drop + store, Value>(obj_id: ObjectID, field_key: address): &mut Value {
同上。

2025-01-04 15:22 UTC, jolestar commented on frameworks/moveos-stdlib/sources/table.move
> +    public fun next<K: copy + drop + store, V:store>(iterator: &mut Iterator<K, V>): &V {
这里应该同时返回 Key。

2025-01-04 15:22 UTC, jolestar commented on frameworks/moveos-stdlib/sources/table.move
> +    public fun list_field_keys<K: copy + drop + store, V:store>(table: &Table<K, V>, cursor: Option<address>, limit: u64): Iterator<K, V> {
cursor 应该是 Option<K>， 然后在内部计算成 field_key。不然调用方不知道如何传递。

2025-01-04 15:22 UTC, jolestar commented on crates/rooch-framework-tests/tests/cases/table/list_field_keys.move
> +        table::list_field_keys(&store.table, option::none(), 10000)
需要一个传递 cursor 的测试用例。

2025-01-05 13:58 UTC, jolestar approved these changes

2025-01-05 13:58 UTC, merged